version: '3.4'
services:
    srb2-kartserv:
        container_name: srb2-kartserv
        ports:
            - '5029:5029/udp'
            - '80:80'
        volumes:
            - '/home/ubuntu/kart:/kart'
        image: jetcodesstuff/srb2-kartserv:latest 